spring.application.name=notification-service
server.port=8085

# Config Server Import
spring.config.import=optional:configserver:http://config-server:8888

# Twilio Configuration
twilio.account_sid=${TWILIO_ACCOUNT_SID:your_account_sid}
twilio.auth_token=${TWILIO_AUTH_TOKEN:your_auth_token}
twilio.phone_number=${TWILIO_PHONE_NUMBER:your_twilio_number}

# Eureka
eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/
eureka.instance.prefer-ip-address=true
