spring.application.name=payment-service
server.port=8084

# Config Server Import
spring.config.import=optional:configserver:http://config-server:8888

# Razorpay credentials (will be pulled from env variables or vault in production)
razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_your_key_here}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:your_secret_here}

# Eureka
eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/
eureka.instance.prefer-ip-address=true
